version: 2
jobs:
  build:
    working_directory: ~/nacl-did
    docker:
      - image: circleci/node:current
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}

      - run:
          name: install-dependencies
          command: |
            npm install

      - run:
          name: test
          command: npm run test:ci

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build